name: faryazan_uploader
description: WebView opener for faryazandecor.com/add with crop + brightness before upload.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.13
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  image: ^4.8.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
